import "./globals.css";

export const metadata = {
  title: "OFATECH - Skill up to earn income",
  description: "Generated by OFATECH",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
